services:
  docusaurus:
    image: kizeo-forms-documentations
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./docs:/app/docs
      - ./i18n:/app/i18n
      - ./src:/app/src
      - ./static:/app/static
      - ./sidebars.js:/app/sidebars.js
      - ./docusaurus.config.js:/app/docusaurus.config.js
      - /app/node_modules
    working_dir: /app
