services:
  docusaurus:
    image: kizeo-forms-documentations
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./docs:/app/docs
      - ./website/i18n:/app/website/i18n
      - ./website/src:/app/website/src
      - ./website/static:/app/website/static
      - ./website/sidebars.js:/app/website/sidebars.js
      - ./website/docusaurus.config.js:/app/website/docusaurus.config.js
      - /app/website/node_modules
    working_dir: /app/website
